version: '2.2'

services:
  db:
    # image compatible pour raspberry pi
    #image: hypriot/rpi-mysql
    image: ubuntu/mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
  phpmyadmin:
    # image compatible pour raspberry pi
    #image: mt08/rpi-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8001:80"
  backend:
    build: backend-django/.
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  mysql-volume: