# Generated by Django 4.0.6 on 2022-07-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systole', models.IntegerField()),
                ('diastole', models.IntegerField()),
                ('date_mesure', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
