# Generated by Django 4.0.6 on 2022-07-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='date_mesure',
            field=models.DateTimeField(),
        ),
    ]
